services:
  # Database service
database: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports: 
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/psql/data

  api: 
    build: 
    ports: 
      - 4000:4000
    environment: 
      DB_USER: $DB_USER
      # Use this if you have a .env.development file
    # DB_PASS: $DB_PASS
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_EXPIRES_IN: 1d
    volumes: 
    - .:/app

  # GraphQL Playground (optional)
  playground: 
    image: hasura/graphql-engine
    restart: always
    ports: 
      - 8080:8080
    environment: 
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${5432}/${DB_NAME}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    volumes: 

volumes: 
  postgres_data: